#!/bin/bash

system_type=$(uname -s)

# Initalize all of the submodules
yadm submodule update --init --recursive

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # install dracula theme in terminal
  open $HOME/.terminal_themes/dracula/Dracula.terminal

  # Install python virtualenv
  pip3 install virtualenv

  # Install the Xcode theme

  mkdir -p ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
  ln -s ~/.xcode-dracula/Dracula.xccolortheme ~/Library/Developer/Xcode/UserData/FontAndColorThemes/Dracula.xccolortheme

elif [ "$system_type" = "Linux" ]; then

  # Install my packages
  sudo apt-get --yes install apt-transport-https bash-completion build-essential curl dconf-cli dconf-editor exfat-fuse gimp git ipython3 libpython3-dev ncdu nfs-common python3-ipython python3-wheel python3-venv syncthing vim

  # Install dracula terminal theme
  ./.gnome-terminal-colors-dracula/install.sh -s Dracula -p Dracula --install-dircolors

  # Install vim plugins
  vim +PluginInstall +qall

  # Mute system sounds
  gsettings set org.gnome.desktop.sound event-sounds false
  
  # Install visual studio code.
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
  sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  sudo apt-get update
  sudo apt-get --yes install code

fi

