#!/bin/bash

system_type=$(uname -s)

# Initalize all of the submodules
yadm submodule update --init --recursive

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # install dracula theme in terminal
  open $HOME/.terminal_themes/dracula/Dracula.terminal

  # Install python virtualenv
  pip3 install virtualenv

elif [ "$system_type" = "Linux" ]; then

  # Install my packages
  sudo apt-get --yes install apt-transport-https bash-completion build-essential darktable dconf-cli exfat-fuse gimp git ipython3 python-gpgme python3-ipython vim

  # Install dracula terminal theme
  ./.gnome-terminal-colors-dracula/install.sh -s Dracula -p Dracula --install-dircolors

  # Install sublime text
  if ! command -v subl >/dev/null 2>&1; then
    echo "Installing sublime text..."
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    sudo apt-get update
    sudo apt-get --yes install sublime-text
    # Configure Package Control
    mkdir -p ~/.config/sublime-text-3/Installed\ Packages
    wget -O ~/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package https://packagecontrol.io/Package%20Control.sublime-package
    # Link to Dropbox
    rm -rf ~/.config/sublime-text-3/Packages/User
    ln -s ~/Dropbox/conf/sublime-text-3/Packages/User ~/.config/sublime-text-3/Packages/User
  fi

  # Install dropbox
  if ! command -v dropbox >/dev/null 2>&1; then
    echo "Installing dropbox..."
    wget -O /tmp/dropbox.deb https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
    sudo apt-get --yes install /tmp/dropbox.deb
  fi


fi
